HOST: http://devel.konkurencia.eu/v1/

--- Konkurencia API v1 ---
---
Api for Konkurencia.eu presentation website.
Api is used mainly in the website front-end, but can be 
useful for other applications.
---

