HOST: http://devel.konkurencia.eu/v1/

--- Konkurencia API v1 ---
---
Api for Konkurencia.eu presentation website.
Api is used mainly in the website front-end, but can be 
useful for other applications.
---

-- Project resources --
---
Lists short details either of all projects, or filtered by section (id supported as parameter)

---
GET /projects/{?section}
> Accept: application/json
< 200
< Content-Type: application/json
{ "projects": [
    { "title": "Web Konkurencie", "shortDescription": "Our web", "mainScreenshot": "/images/projects/project_1.jpg", "url": "/projects/1/"}
    ]}

---
Returns all info about a project specified by {id}.

---
GET /projects/{id}/
> Accept: application/json
< 200
< Content-Type: application/json
{ "title": "Web Konkurencie", "shortDescription": "Our web", "longDescription": "Our awesome web", "uri": "http://konkurencia.eu",
"screenshots": ["/images/projects/project_1.jpg", "/images/projects/project_2.jpg", "/images/projects/project_3.jpg"],
"tags": [{"url": "/tags/1/", "tag": "HTML"}, {"url": "/tags/2/", "tag": "PHP"}, {"url": "/tags/3/", "tag": "CSS"}],
"people": [{"name": "Ondrej Job", "url": "/people/1/"}, {"name": "Matej Zilak", "url": "/people/2/"}],
"relatedProjects": [{ "title": "Web Konkurencie", "shortDescription": "Our web", "mainScreenshot": "/images/projects/project_1.jpg", "url": "/projects/1/"}]
"date": "YYYY-MM-DD HH:MM:SS"
}

-- People resources --
---
Lists short details of all people of Konkurencia, or filtered by section (id supported as parameter)

---
GET /people/{?section}
> Accept: application/json
< 200
< Content-Type: application/json
{ "people": [
    {"name": "Ondrej Job", "url": "/people/1/", "photo": "/images/people/ondro.jpg",
    "mainSection": {"url": "/sections/1/", "name": "Webdesign"},
    }
]}

---
Returns all details for a person specified by {id}

The last "social" object contains only populated fields from DB.

---
GET /people/{id}/
> Accept: application/json
< 200
< Content-Type: application/json
{
    "name": "Ondrej Job", "photo": "/images/people/ondro.jpg",
    "mainSection": {"url": "/sections/1/", "name": "Webdesign"},
    "sections": [{"url": "/sections/1/", "name": "Webdesign"}, {"url": "/sections/2/", "name": "Design"}],
    "shortDesc": "Super Awesome Type Designer",
    "motto": "Nieto fontu bez pismenok, mudrost pravi.",
    "tags": [{"url": "/tags/1/", "tag": "HTML"}, {"url": "/tags/2/", "tag": "PHP"}, {"url": "/tags/3/", "tag": "CSS"}],
    "projects": [{ "title": "Web Konkurencie", "shortDescription": "Our web", "mainScreenshot": "/images/projects/project_1.jpg", "url": "/projects/1/"}],
    "social": {"web": "http://urtd.net", "mail": "ondro@konkurencia.eu", "facebook": "http://fb.com/urtd/"}
}

-- Tags resource --
---
Lists all existing tags

---
GET /tags/
> Accept: application/json
< 200
< Content-Type: application/json
{
    "tags": [
    {"url": "/tags/1/", "tag": "HTML"},
    {"url": "/tags/2/", "tag": "PHP"},
    {"url": "/tags/3/", "tag": "CSS"}
    ]
}

---
Tag detail specified by {id}, showing what projects and people tag belongs to

---
GET /tags/{id}/
> Accept: application/json
< 200
< Content-Type: application/json
{
    "projects": [{ "title": "Web Konkurencie", "shortDescription": "Our web", "mainScreenshot": "/images/projects/project_1.jpg", "url": "/projects/1/"}],
    "people": [{"name": "Ondrej Job", "url": "/people/1/"}, {"name": "Matej Zilak", "url": "/people/2/"}]
}

-- Quotes resource --
---
Gets random quote for section

---
GET /quotes/random/{?section}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "quote": "Veni, Vidi, Vici"
}

-- Section resources --
---
Lists all resources

---
GET /sections/
> Accept: application/json
< 200
< Content-Type: application/json
{
    "sections": [
    {"url": "/sections/1/", "name": "Webdesign", "icon": "/images/sections/1.jpg", "description": "webz"},
    {"url": "/sections/2/", "name": "Design", "icon": "/images/sections/2.jpg", "description": "stuff"}
    ]
}

---
Section details

---
GET /section/{id}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "name": "Webdesign",
    "icon": "/images/sections/1.jpg",
    "description": "webz",
    "motivation": "we do webz da best"
}